id = "abap"
name = "ABAP"
description = "ABAP language support: syntax highlighting, bracket matching, and document outline"
version = "0.0.1"
schema_version = 1
authors = ["Oscar Jauregui <ojauregui@gmail.com>"]
repository = "https://github.com/oajauregui/zed-abap"

[grammars.abap]
repository = "https://github.com/oajauregui/tree-sitter-abap"
rev = "29f45406f8fe37f7e3ef7efdeeba270bcc7a9143"
