id = "abap"
name = "ABAP"
description = "ABAP language support: syntax highlighting, bracket matching, and document outline"
version = "0.0.1"
schema_version = 1
authors = ["Oscar Jauregui <ojauregui@gmail.com>"]
repository = "https://github.com/oajauregui/zed-abap"

[grammars.abap]
repository = "https://github.com/oajauregui/tree-sitter-abap"
rev = "83d16ad3d8e5f49a7d2b9da805ad989a38f6f42f"
